name: Deploy Server

on:
    push:
        branches: [ main ]

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
        - name: Deploy to Remote Server
          uses: appleboy/ssh-action@v1.2.0
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.KEY }}
            passphrase: ${{ secrets.PASSPHRASE }}
            request_pty: true
            script: |
                cd /var/www/html/argon/server
                git reset --hard origin/main
                git pull origin main
                bun install
                pm2 start ecosystem.config.cjs